language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION nose
  - source activate test-environment
  - conda install mkl-service=2017
  - conda install -c conda-forge pymc3
  - python setup.py install

script:
  # Check if numpy and pymc are ok before testing fbu
  - time python -c 'import numpy as np; print(np.array([1,2,3]).shape)'
  - time python -c 'import pymc3'
  - nosetests -vv fbu.tests.test_basic