language: python

python:
  - "2.7"

install:
  # perhaps we could use the system libraries?
  # sudo apt-get install python-numpy python-scipy python-matplotlib ipython ipython-notebook python-pandas python-sympy python-nose

  # do we really need to specify the versions? they don't do it at github.com/pymc-devs/pymc
  time pip install numpy
  time pip install matplotlib==1.3.0
  time pip install nose==1.3.0
  time pip install pymc==2.2
  time pip install pyparsing==2.0.1
  time pip install python-dateutil==2.1
  time pip install scipy==0.12.0
  time pip install six==1.3.0
  time pip install tornado==3.1
  time pip install wsgiref==0.1.2

script:

  # Check if numpy and pymc are ok
  - time python -c 'import numpy as np; print np.array([1,2,3]).shape'
  - time python -c 'import pymc'

  # Check that the fbu modules can be imported
  # TBD

  # Now run the tests
  - tests/dummy.py

